services:
  mongodb:
    image: mongo:latest # use the latest image
    container_name: mongo-db
    restart: unless-stopped
    environment: # set required env variables to access mongo
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes: #optional to preserve database after container is deleted.
      - ./database-data:/data/db

  # Mongo Express Service
  mongo-express:
    image: mongo-express:latest
    container_name: mongoExpress
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb # use the name of mongo container
    depends_on:
      - mongodb

  redck-restaurant-ms-manager:
    build:
      context: /restaurant-ms-manager
      dockerfile: Dockerfile
    container_name: restaurant-ms-manager
    image: redck-restaurant-ms-manager.jar
    ports:
      - "8181:8181"
    depends_on:
      - mongo-express
      - mongodb


